package votacaocolegiado;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Afastamento.java
//  @ Date : 08/06/2012
//  @ Author : 
//
//

public class Afastamento extends Votacao {
	private String justificativa;
	private String encargosDidaticos;
	private String encargosAdmin;

	public Afastamento(String titulo) {
		super(titulo);
		this.encargosAdmin = null;
		this.encargosDidaticos = null;
		this.justificativa = null;
//		super.tipo = 'A';
	}

	public void insereDocumentos(String justificativa,
			String encargosDidaticos, String encargosAdmin) {
		this.justificativa = justificativa;
		this.encargosDidaticos = encargosDidaticos;
		this.encargosAdmin = encargosAdmin;
	}

	public void lerVotacao() {
		super.lerVotacao();
		System.out.println("Justificativo: " + this.justificativa);
		System.out.println("\nEncargos didáticos: " + this.encargosDidaticos);
		System.out.println("\nEncargos administrativos: " + this.encargosAdmin);
	}

	public String getJustificativa() {
		return this.justificativa;
	}

	public String getEncDitaticos() {
		return this.encargosDidaticos;
	}

	public String getEncAdmin() {
		return this.encargosAdmin;
	}
}
