package votacaocolegiado;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ata.java
//  @ Date : 08/06/2012
//  @ Author : 
//
//

public class Ata {
	private String texto;
	private String titulo;

	public Ata(ArrayList<Voto> favoravel, ArrayList<Voto> naoFavoravel,
			ArrayList<Voto> abstem, String titulo) {
		texto = "------ATA DA VOTAÇÂO "+titulo+"-----"				
			    + "\nVotos favoraveis: " + favoravel.size()
				+ "\nVotos não favoráveis: " + naoFavoravel.size()
				+ "\nVotos abstem: " + abstem.size();
		this.titulo = titulo;
	}

	public String getTexto() {
		return this.texto;
	}
	
	public String getTitulo()
	{
		return this.titulo;
	}
}
