package votacaocolegiado;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EstagioProbatorio.java
//  @ Date : 08/06/2012
//  @ Author : 
//
//

public class EstagioProbatorio extends Votacao {
	private String relatorio;
	private String parecer;

	public EstagioProbatorio(String titulo) {
		super(titulo);
		this.parecer = null;
		this.relatorio = null;
		// super.tipo = 'E';
	}

	public void insereDocumentos(String relatorio, String parecer) {
		this.relatorio = relatorio;
		this.parecer = parecer;
	}

	public String getRelatorio() {
		return this.relatorio;
	}

	public String getParecer() {
		return this.parecer;
	}

	public void lerVotacao() {
		super.lerVotacao();
		System.out.println("Relatório: " + this.relatorio);
		System.out.println("Parecer: " + this.parecer);
	}
}
