package votacaocolegiado;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

import votacaocolegiado.Usuario.EnumAcoes;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Secretaria.java
//  @ Date : 08/06/2012
//  @ Author : 
//
//


public class Secretaria extends Usuario {
	// public Votacao Cria;


	public Secretaria(String nome, int matricula, String senha) {
		super(nome, matricula, senha);
		
		acoes.add(EnumAcoes.CriarVotacao);
	}

	public void criarVotacao(ArrayList<Votacao> listaVotacoes) {
		int opcao = 0;
		String titulo = null;
		Scanner scannerInt = new Scanner(System.in);
		Scanner scannerString = new Scanner(System.in);

		System.out.println("Opção 1: Estagio Probatorio");
		System.out.println("Opção 2: Progresso Funcional");
		System.out.println("Opção 3: Afastamento");
		System.out.println("Qual votação deseja criar?");

		try {
			opcao = scannerInt.nextInt();

			System.out.print("Insira o titulo da votação: ");
			titulo = scannerString.nextLine();

			switch (opcao) {
			case 1:// Estagio Probatorio
				String relatorioEstagio = null;
				String parecer = null;
				EstagioProbatorio novoEstagio = new EstagioProbatorio(titulo);
				System.out.println("Insira o relatório:");
				relatorioEstagio = scannerString.nextLine();
				System.out.println("Insira o parecer:");
				parecer = scannerString.nextLine();
				novoEstagio.insereDocumentos(relatorioEstagio, parecer);
				listaVotacoes.add(novoEstagio);
				break;
			case 2:// Progressão Funcional
				String relatorioProgressao = null;
				String parecerComissao = null;
				ProgressaoFuncional novaProgressao = new ProgressaoFuncional(
						titulo);
				System.out.println("Insira o relatório:");
				relatorioProgressao = scannerString.nextLine();
				System.out.println("Insira o parecer da comissão:");
				parecerComissao = scannerString.nextLine();
				novaProgressao.insereDocumentos(relatorioProgressao,
						parecerComissao);
				listaVotacoes.add(novaProgressao);
				break;
			case 3:// Afastamento
				String justificativa = null;
				String encargosDidaticos = null;
				String encargosAdmin = null;
				Afastamento novoAfastamento = new Afastamento(titulo);
				System.out.println("Insira a justificativa:");
				justificativa = scannerString.nextLine();
				System.out.println("Insira os engargos didáticos");
				encargosDidaticos = scannerString.nextLine();
				System.out.println("Insira os encargos adimnistrativos");
				encargosAdmin = scannerString.nextLine();
				novoAfastamento.insereDocumentos(justificativa,
						encargosDidaticos, encargosAdmin);
				listaVotacoes.add(novoAfastamento);
				break;
			default:
				System.out.println("Opção inválida");

			}
		} catch (InputMismatchException e) {
			System.out.println("Entrada inválida.");
		}
	}

}
