package votacaocolegiado;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Votacao.java
//  @ Date : 08/06/2012
//  @ Author : 
//
//

public abstract class Votacao {
	private String titulo;
	private boolean estaAberta = false;
	private ArrayList<Voto> favoravel = new ArrayList<Voto>();
	private ArrayList<Voto> naoFavoravel = new ArrayList<Voto>();
	private ArrayList<Voto> abstem = new ArrayList<Voto>();
	public Ata Gera;

	public Votacao(String titulo) {
		this.titulo = titulo;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public int votosFavoraveis() {
		return favoravel.size();
	}

	public int votosNaoFavoraveis() {
		return naoFavoravel.size();
	}

	public int votosAbstencao() {
		return abstem.size();
	}

	private boolean usuarioJaVotou(MembroColegiado membro) {
		for (int i = 0; i < votosFavoraveis(); i++)
			if (favoravel.get(i).getUsuario() == membro)
				return true;
		for (int i = 0; i < votosNaoFavoraveis(); i++)
			if (naoFavoravel.get(i).getUsuario() == membro)
				return true;
		for (int i = 0; i < votosAbstencao(); i++)
			if (abstem.get(i).getUsuario() == membro)
				return true;
		return false;
	}

	public boolean votacaoAberta() {
		return this.estaAberta;
	}

	public void setEstaAberta() {
		this.estaAberta = true;
	}

	public Ata gerarAta() {
		return new Ata(favoravel, naoFavoravel, abstem, this.titulo);
	}

	public void documentacaoRecebida() {

	}

	public void insereDocumentos() {

	}

	public void insereVoto(MembroColegiado membroColegiado) throws UsuarioJaVotouException,
			votacaoFechadaException {

		int tipoVoto = 0;
		String justificativa = null;
		Scanner scanner = new Scanner(System.in);

		if (usuarioJaVotou(membroColegiado))
			throw new UsuarioJaVotouException();
		if (!votacaoAberta())
			throw new votacaoFechadaException();

		System.out.println("Opção 1: favorável");
		System.out.println("Opção 2: não favorável");
		System.out.println("Opção 3: abstem");
		System.out.println("Opção 4: sair");
		System.out.print("Sua opção: ");

		try {
			tipoVoto = scanner.nextInt();
			switch (tipoVoto) {
			case 1:
				favoravel.add(new Voto("favoravel", justificativa, membroColegiado));
				break;
			case 2:
				naoFavoravel.add(new Voto("naoFavoravel", justificativa, membroColegiado));
				break;
			case 3:
				abstem.add(new Voto("abstem", justificativa, membroColegiado));
				break;
			default:
				System.out.println("Opção inválida");
			}
		} catch (InputMismatchException e) {
			System.out.println("Valor entrado é inválido");

		}
	}

	public void lerVotacao() {
		System.out.println("Titulo da votação: " + this.titulo);
	}
}
