package votacaocolegiado;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Voto.java
//  @ Date : 08/06/2012
//  @ Author : 
//
//

public class Voto {
	private String tipo;
	private String justificativa;
	private MembroColegiado membro;

	public Voto(String tipo, String justificativa, MembroColegiado membro)
	{
		this.tipo = tipo;
		this.justificativa = justificativa;
		this.membro = membro;
	}
	
	public String getTipo() {
		return tipo;
	}

	public String getjustificativa() {
		return justificativa;
	}

	public MembroColegiado getUsuario() {
		return this.membro;
	}

}
